### ISSUE TITLE
This function has been renamed 

### ISSUE THREAD

**Issue by alonks1234** [Improbable-AI/airobot#16]
https://github.com/Improbable-AI/airobot/blob/8277fa242ed188858c0834d5b32e7a7a12b80058/src/airobot/utils/common.py#L57

**Comment by alonks1234** [comment]
see https://stackoverflow.com/questions/65628149/ratcave-scipy-spatial-transform-rotation-rotation-object-has-no-attribute-a

**Comment by taochenshh** [comment]
Thanks for pointing it out. We have fixed that in the `qa` branch. You can use that instead.
