### ISSUE TITLE
Example link broken on README

### ISSUE THREAD

**Issue by DanielTakeshi** [Improbable-AI/airobot#22]
Hello,

In the "Getting Started" section of the README, it says:

```
A sample script is shown below. You can find more examples here
```

The link to the examples goes to here: https://github.com/Improbable-AI/airobot/examples

which does not exist. I'm guessing you mean:

https://github.com/Improbable-AI/airobot/tree/master/examples

?

**Comment by taochenshh** [comment]
Thanks for letting us know. We have fixed the link.
