### ISSUE TITLE
Example with simulated YuMi uses outdated gripper methods

### ISSUE THREAD

**Issue by DanielTakeshi** [Improbable-AI/airobot#24]
**Describe the bug**
If you run the simulation example with the YuMi:

```
python examples/yumi/sim/joint_position_control.py
```

It seems like there are some outdated methods, as reported later. These happen when calling:

https://github.com/Improbable-AI/airobot/blob/57a6b19bd2bd71b7c3abceed1ac58766608e556a/examples/yumi/sim/joint_position_control.py#L33-L37

The end effector tool `robot.arm.left_arm.eetool` is calling `set_pos`. However, from searching the code base (e.g., using GitHub or in vscode) I only see `set_pos` defined in this class:

https://github.com/Improbable-AI/airobot/blob/57a6b19bd2bd71b7c3abceed1ac58766608e556a/src/airobot/ee_tool/robotiq2f140_real.py#L19-L31

For a special gripper for the UR5 robot (and not for the YuMi). The end effector tool in the `examples/yumi/sim/joint_position_control.py` script is from this class:

https://github.com/Improbable-AI/airobot/blob/57a6b19bd2bd71b7c3abceed1ac58766608e556a/src/airobot/ee_tool/yumi_parallel_jaw_pybullet.py#L4-L27

and from searching the parent classes, it seems like there is no `set_pos` anywhere, or `get_pos` as well.

**To Reproduce**
1. Create a clean conda environment with Python 3.7. Follow instructions in the current README.
2. Run `python examples/yumi/sim/joint_position_control.py`.
3. The error message is as follows:

```
Traceback (most recent call last):
  File "examples/yumi/sim/joint_position_control.py", line 54, in <module>
    main()
  File "examples/yumi/sim/joint_position_control.py", line 39, in main
    robot.arm.left_arm.eetool.set_pos(0.005)
AttributeError: 'YumiParallelJawPybullet' object has no attribute 'set_pos'
```

Even if that line of code is commented out, the `get_pos` method also does not seem to be defined:

```
Traceback (most recent call last):
  File "examples/yumi/sim/joint_position_control.py", line 54, in <module>
    main()
  File "examples/yumi/sim/joint_position_control.py", line 41, in main
    ar.log_info(np.round(robot.arm.left_arm.eetool.get_pos(), 6))
AttributeError: 'YumiParallelJawPybullet' object has no attribute 'get_pos'
```

I was able to get the code to run without errors with these changes:

- set_pos() --> set_jpos()
- get_pos() --> get_jpos()

Is this the correct intended behavior?

**Expected behavior**
I expect to see no errors when running the script.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Code version: master branch as of commit https://github.com/Improbable-AI/airobot/commit/57a6b19bd2bd71b7c3abceed1ac58766608e556a

**Additional context**
I'm sure that this is just a matter of updating the API. I just wanted to report this so that the examples all run correctly.

**Comment by taochenshh** [comment]
Thanks for reporting this. Fixed in commit 14463fa6629faafdf986d9ad28b8906598bad534
