### ISSUE TITLE
UR10 with 2F140

### ISSUE THREAD

**Issue by saslamaa** [Improbable-AI/airobot#26]
How can a new robot be added in this existing library? For example, I want to use UR10 with 2f140.
I tried to add the URDF of ur10, but it seems it requires some other changes as well.

**Comment by taochenshh** [comment]
Hi,

You can add a new robot by adding its urdf. You can check out the example URDFs [here](https://github.com/Improbable-AI/airobot/tree/master/src/airobot/urdfs). After that, you might want to create a new config file for the new robot. Example config files are [here](https://github.com/Improbable-AI/airobot/blob/master/src/airobot/cfgs/ur5e_2f140_cfg.py#L16)
